### ISSUE TITLE
kube-explorer自动创建shell pod的tolerations问题

### ISSUE THREAD

**Issue by xshrim** [niusmallnan/kube-explorer#27]
版本：kubernetes v1.25.3  kube-explorer v0.2.12

打开 kubectl shell 会创建shell pod，但pod的tolerations配置的是
```yaml
- effect: NoSchedule
    key: node-role.kubernetes.io/controlplane
    operator: Equal
    value: "true"
```

但使用kubeadm创建的集群的master节点上配置的taint是`node-role.kubernetes.io/control-plane:NoSchedule`，因此会导致shell pod无法部署，能否使此工具支持kubeadm创建的单节点集群。

复现步骤
kubeadm部署单节点集群
进入 kube-explorer
点击右上角 kubectl shell
kubectl -n kube-system describe pod dashboard-shell-xxxxx
